### ISSUE TITLE
radeontop not detected

### ISSUE THREAD

**Issue by Paullux** [lestofante/ksysguard-gpu#10]
```
 **paulw  paul-MS-7978  ~  $ ** sudo python3 /usr/bin/gpuStatsServer.py
Traceback (most recent call last):
  File "/usr/bin/gpuStatsServer.py", line 70, in run
    self.p = subprocess.Popen(exe, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'intel_gpu_top': 'intel_gpu_top'
intel_gpu_top process has died! probably is not installed, or need root
Traceback (most recent call last):
  File "/usr/bin/gpuStatsServer.py", line 174, in run
    self.p = subprocess.Popen(exe, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi': 'nvidia-smi'
nvidia-smi process has died! probably is not installed, or need root
Traceback (most recent call last):
  File "/usr/bin/gpuStatsServer.py", line 128, in run
    self.parseLine(line)
  File "/usr/bin/gpuStatsServer.py", line 113, in parseLine
    self.allGpu[gpuName+"."+keyValue[1]+'.%'] = val[:-1] #remove . and %
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
radeontop process has died! probably is not installed, or need root
No data source is alive

```

**Comment by lestofante** [comment]
Hi, could you please run radeontop -d-
and post here the result?

To me looks like the output format is not understood, the error is not FileNotFoundError but co,ming from the parsing (TypeError)

**Comment by lestofante** [comment]
close for missing update, also new revision of the code has been released
