### ISSUE TITLE
Not working on nvidia driver version 520.56.06

### ISSUE THREAD

**Issue by Ex0danify** [lestofante/ksysguard-gpu#27]
Hey there, I'm really interested in using your neat little script here. Sadly I am unable to run it, I guess due to a changed output of nvidia-smi.

I also tried the developer branch, same issue there.

**System:**
**OS:** Manjaro Linux
**Kernel:** 6.1.0-1-MANJARO
**GPU:** Nvidia RTX3080 TI
**NVIDIA Driver:** 520.56.06
**Python:** 3.10

**Script Error:**
```
intel_gpu_top: executable not found
intel_gpu_top: process stopped
radeontop: executable not found
radeontop: process stopped
nvidia-smi: found and running
nvidia-smi: exception while parsing the line, please report the bug b'\n'
Traceback (most recent call last):
  File "/srv/ex0/ksysguard-gpu/src/ksysguard-gpu.py", line 39, in run
    self.parser.parseLine(line)
  File "/srv/ex0/ksysguard-gpu/src/nvidia.py", line 20, in parseLine
    if not parameters[0].isdigit():
IndexError: list index out of range
intel_gpu_top: terminated
radeontop: terminated
nvidia-smi: process stopped
```

**Output nvidia-smi:**

```
Thu Nov 17 18:21:27 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:43:00.0  On |                  N/A |
|  0%   54C    P8    38W / 350W |   1637MiB / 12288MiB |     17%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1198      G   /usr/lib/Xorg                      36MiB |
|    0   N/A  N/A      1316      G   /usr/bin/kwalletd5                  3MiB |
|    0   N/A  N/A      1338      G   /usr/bin/kwin_wayland             446MiB |
|    0   N/A  N/A      1380      G   /usr/bin/Xwayland                  14MiB |
|    0   N/A  N/A      1404      G   /usr/bin/ksmserver                  3MiB |
|    0   N/A  N/A      1406      G   /usr/bin/kded5                      3MiB |
|    0   N/A  N/A      1464      G   ...de-authentication-agent-1        3MiB |
|    0   N/A  N/A      1466      G   ...ib/xdg-desktop-portal-kde        3MiB |
|    0   N/A  N/A      1681      G   /usr/bin/msm_kde_notifier           3MiB |
|    0   N/A  N/A      1687      G   /usr/lib/kdeconnectd                3MiB |
|    0   N/A  N/A      1693      G   /usr/bin/yakuake                    3MiB |
|    0   N/A  N/A      1707      G   /usr/bin/kaccess                    3MiB |
|    0   N/A  N/A      1713      G   /usr/lib/DiscoverNotifier           3MiB |
|    0   N/A  N/A      1714      G   /usr/bin/kalendarac                 3MiB |
|    0   N/A  N/A      1802      G   /usr/bin/akonadi_control            3MiB |
|    0   N/A  N/A      2253      G   ...RendererForSitePerProcess       35MiB |
|    0   N/A  N/A      2259      G   ...akonadi_akonotes_resource        3MiB |
|    0   N/A  N/A      2260      G   ...konadi_birthdays_resource        3MiB |
|    0   N/A  N/A      2261      G   ...akonadi_contacts_resource        3MiB |
|    0   N/A  N/A      2262      G   ...bin/akonadi_ical_resource        3MiB |
|    0   N/A  N/A      2263      G   ...bin/akonadi_imap_resource        3MiB |
|    0   N/A  N/A      2304      G   ...in/akonadi_indexing_agent        3MiB |
|    0   N/A  N/A      2308      G   .../akonadi_maildir_resource        3MiB |
|    0   N/A  N/A      2312      G   ...nadi_maildispatcher_agent        3MiB |
|    0   N/A  N/A      2313      G   ...n/akonadi_migration_agent        3MiB |
|    0   N/A  N/A      2322      G   ...adi_newmailnotifier_agent        3MiB |
|    0   N/A  N/A      2325      G   /usr/bin/akonadi_notes_agent        3MiB |
|    0   N/A  N/A      3771      G   /usr/lib/baloorunner                3MiB |
|    0   N/A  N/A      4244      G   /usr/lib/kf5/kiod5                  3MiB |
|    0   N/A  N/A      4469      G   /usr/bin/telegram-desktop           3MiB |
|    0   N/A  N/A      9154      G   ...830507259415158311,131072       37MiB |
|    0   N/A  N/A     14466      G   /usr/bin/plasmashell              369MiB |
|    0   N/A  N/A     15223      G   /usr/lib/firefox/firefox          305MiB |
|    0   N/A  N/A     15478      G   ...-browser-integration-host        3MiB |
|    0   N/A  N/A     18515      G   .../bin/plasma-systemmonitor       43MiB |
|    0   N/A  N/A     18583      G   /usr/bin/ksysguard                  3MiB |
+-----------------------------------------------------------------------------+

```

**Comment by lestofante** [comment]
unfortunately the command want a list of field to show, but this list is different depending on the GPU and i could not find a way to list them.

nvidia-smi --query-gpu=index,temperature.gpu,utilization.gpu,utilization.memory,fan.speed,pstate,power.draw,clocks.sm,clocks.mem,clocks.gr --format=csv -l 1

is the full command , notice i request the data in csv format, as the output as shown would be a pain to parse.
If you could post that output, i can try to see if i can fix it somehow

**Comment by Ex0danify** [comment]
Thanks for the response man, highly appreciated!

Here is the output of the command requested:
```
index, temperature.gpu, utilization.gpu [%], utilization.memory [%], fan.speed [%], pstate, power.draw [W], clocks.current.sm [MHz], clocks.current.memory [MHz], clocks.current.graphics [MHz]
0, 56, 26 %, 4 %, 34 %, P3, 83.92 W, 1320 MHz, 5001 MHz, 1320 MHz
0, 55, 25 %, 4 %, 34 %, P3, 78.22 W, 1470 MHz, 5001 MHz, 1470 MHz
0, 56, 24 %, 4 %, 34 %, P3, 84.77 W, 1470 MHz, 5001 MHz, 1470 MHz
0, 55, 26 %, 4 %, 34 %, P3, 78.63 W, 1410 MHz, 5001 MHz, 1410 MHz
0, 55, 27 %, 4 %, 34 %, P3, 83.67 W, 1410 MHz, 5001 MHz, 1410 MHz
0, 55, 28 %, 4 %, 34 %, P3, 77.39 W, 1275 MHz, 5001 MHz, 1275 MHz
0, 55, 29 %, 4 %, 34 %, P3, 82.81 W, 1275 MHz, 5001 MHz, 1275 MHz
0, 55, 30 %, 4 %, 34 %, P3, 77.00 W, 1245 MHz, 5001 MHz, 1245 MHz
0, 55, 28 %, 4 %, 34 %, P3, 82.64 W, 1245 MHz, 5001 MHz, 1245 MHz
0, 55, 32 %, 4 %, 34 %, P3, 76.64 W, 1185 MHz, 5001 MHz, 1185 MHz
0, 55, 28 %, 4 %, 34 %, P3, 82.40 W, 1185 MHz, 5001 MHz, 1185 MHz
0, 55, 23 %, 4 %, 34 %, P3, 77.80 W, 1440 MHz, 5001 MHz, 1440 MHz
0, 55, 25 %, 4 %, 34 %, P3, 83.43 W, 1440 MHz, 5001 MHz, 1440 MHz

```
