### ISSUE TITLE
Handle nvidia-smi output when blacklisting nvidia module

### ISSUE THREAD

**Issue by davidalb97** [lestofante/ksysguard-gpu#29]
## The problem

When `nvidia-smi` cannot access the `nvidia` module, it will return `9` and output the following into to the stdout:
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

Example:
```
nvidia-smi --query-gpu=index,temperature.gpu,utilization.gpu,utilization.memory,fan.speed,pstate,power.draw,clocks.sm,clocks.mem,clocks.gr --format=csv -l1
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

The following is the journalctl output:
```
mar 12 11:46:54 user kernel: Module nvidia is blacklisted
mar 12 11:46:54 user ksysguard-gpu.py[1707]: Traceback (most recent call last):
mar 12 11:46:54 user ksysguard-gpu.py[1707]:   File "/usr/bin/ksysguard-gpu.py", line 188, in run
mar 12 11:46:54 user ksysguard-gpu.py[1707]:     self.parser.parseLine(line)
mar 12 11:46:54 user ksysguard-gpu.py[1707]:   File "/usr/bin/ksysguard-gpu.py", line 136, in parseLine
mar 12 11:46:54 user ksysguard-gpu.py[1707]:     if not parameters[0].isdigit():
mar 12 11:46:54 user ksysguard-gpu.py[1707]: IndexError: list index out of range
```

This could be fixed by either checking if `parameters` is empty before `nvidia.py` line `20` or checking the return value of the command.

## My use case
Having nvidia-sli installed with nvidia module blacklisted might come across as an odd behavior,
in my case, I select which driver I boot with with grub command line kernel parameters (either `nvidia` ou `nouveu`).
Because `nvidia-smi` does not support the `nouveu` driver, I get my journalctl output plagued by thousands of these stacktraces,
and I would rather have no stacktrace when I am not even using the nvidia driver.
I think that a single warning / stacktrace explaining that `nvidia-smi` could not be used for the first time would be better than thousands of  warnings / stacktraces.

## PS
Because of the way the `intel.py` script is also directly accessing the array index, this problem might occur also on `Intel.parseLine()` func (line 42). As I do not use Inter hardware myself, neither understand how `intel_gpu_top` works, I cannot confirm it.

**Comment by davidalb97** [comment]
Closing this issue as a fix for it has been merged to the master branch on #30 .
